name: demo

services:
  postgres:
    container_name: demo-postgres
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./docker/postgres/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - demo

networks:
  demo:
    driver: bridge
